version: '3.1'

services:

  db-inventario:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    
    # Este comando no hace falta con la version 9
    # command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: zx76wbz7FG89k
    ports:
      - 33306:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8181:8080
